Traceback (most recent call last):
  File "C:\Users\biagi\anaconda3\envs\book\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\biagi\anaconda3\envs\book\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\biagi\anaconda3\envs\book\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\biagi\anaconda3\envs\book\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\biagi\anaconda3\envs\book\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\biagi\anaconda3\envs\book\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\biagi\anaconda3\envs\book\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Plot the decision tree
plt.figure(figsize=(12, 8))
plot_tree(tree_clf, filled=True, feature_names=["Na to K", "Age"], class_names=["Drug A", "Drug B", "Drug C"], rounded=True)
plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[6], line 3[0m
[0;32m      1[0m [38;5;66;03m# Plot the decision tree[39;00m
[0;32m      2[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m12[39m, [38;5;241m8[39m))
[1;32m----> 3[0m plot_tree(tree_clf, filled[38;5;241m=[39m[38;5;28;01mTrue[39;00m, feature_names[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mNa to K[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mAge[39m[38;5;124m"[39m], class_names[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mDrug A[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mDrug B[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mDrug C[39m[38;5;124m"[39m], rounded[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m      4[0m plt[38;5;241m.[39mshow()

[1;31mNameError[0m: name 'tree_clf' is not defined

